// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/consensus.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message sent when a node wants to enter critical section
type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // ID of the requesting node
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // Lamport timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_proto_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RequestMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Reply message sent to grant permission
type ReplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // ID of the replying node
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // Lamport timestamp
	Granted       bool                   `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`             // Permission granted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_proto_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_proto_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReplyMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReplyMessage) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

var File_proto_consensus_proto protoreflect.FileDescriptor

const file_proto_consensus_proto_rawDesc = "" +
	"\n" +
	"\x15proto/consensus.proto\x12\tconsensus\"G\n" +
	"\x0eRequestMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"_\n" +
	"\fReplyMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\agranted\x18\x03 \x01(\bR\agranted2P\n" +
	"\x0fMutualExclusion\x12=\n" +
	"\aRequest\x12\x19.consensus.RequestMessage\x1a\x17.consensus.ReplyMessageB!Z\x1fmand4-consensus/proto/consensusb\x06proto3"

var (
	file_proto_consensus_proto_rawDescOnce sync.Once
	file_proto_consensus_proto_rawDescData []byte
)

func file_proto_consensus_proto_rawDescGZIP() []byte {
	file_proto_consensus_proto_rawDescOnce.Do(func() {
		file_proto_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consensus_proto_rawDesc), len(file_proto_consensus_proto_rawDesc)))
	})
	return file_proto_consensus_proto_rawDescData
}

var file_proto_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_consensus_proto_goTypes = []any{
	(*RequestMessage)(nil), // 0: consensus.RequestMessage
	(*ReplyMessage)(nil),   // 1: consensus.ReplyMessage
}
var file_proto_consensus_proto_depIdxs = []int32{
	0, // 0: consensus.MutualExclusion.Request:input_type -> consensus.RequestMessage
	1, // 1: consensus.MutualExclusion.Request:output_type -> consensus.ReplyMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_consensus_proto_init() }
func file_proto_consensus_proto_init() {
	if File_proto_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consensus_proto_rawDesc), len(file_proto_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consensus_proto_goTypes,
		DependencyIndexes: file_proto_consensus_proto_depIdxs,
		MessageInfos:      file_proto_consensus_proto_msgTypes,
	}.Build()
	File_proto_consensus_proto = out.File
	file_proto_consensus_proto_goTypes = nil
	file_proto_consensus_proto_depIdxs = nil
}
